language: node_js
cache: yarn
dist: bionic

jobs:
  include:
  ## TEST STAGE

  # Test main OSes on Node 10.x branch.
  - os: linux
    node_js: "10.16"
    env: INCLUDE_COMPAT_TESTS=true

  - os: linux
    env: ALPINE_CHROOT=3.10 INCLUDE_COMPAT_TESTS=true
    sudo: required

  - os: osx
    node_js: "10.16"

  - os: windows
    node_js: "10.16"
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    env: YARN_GPG=no

  - os: windows
    node_js: "10.16/x86"
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    env: YARN_GPG=no

  # Test shared libraries on Linux and macOS.
  - os: linux
    node_js: "10.16"
    env: ZMQ_SHARED=true
    addons: {apt: {packages: libzmq3-dev}}

  - os: osx
    node_js: "10.16"
    env: ZMQ_SHARED=true
    addons: {homebrew: {packages: zeromq, update: true}}

  # Test older versions of ZMQ.
  - os: linux
    node_js: "10.16"
    env: ZMQ_VERSION=4.2.4

  # Test recent Node versions.
  - os: linux
    node_js: "12"
    env: INCLUDE_COMPAT_TESTS=true

  - os: linux
    node_js: "13"

  ## PREBUILD STAGE

  - stage: prebuild
    os: linux
    env: ARCHIVE_SUFFIX=-x64
    node_js: "10.16"
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: linux
    env: ALPINE_CHROOT=3.10 ARCHIVE_SUFFIX=-x64-musl
    sudo: required
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: linux
    node_js: "10.16"
    env: ARCH=arm TRIPLE=arm-linux-gnueabihf GCC=8 ARCHIVE_SUFFIX=-armv7
    addons: {apt: {packages: [gcc-8-arm-linux-gnueabihf, g++-8-arm-linux-gnueabihf]}}
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: linux
    node_js: "10.16"
    env: ARCH=arm64 TRIPLE=aarch64-linux-gnu GCC=8 ARCHIVE_SUFFIX=-armv8
    addons: {apt: {packages: [gcc-8-aarch64-linux-gnu, g++-8-aarch64-linux-gnu]}}
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: osx
    node_js: "10.16"
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: windows
    node_js: "10.16"
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    env: YARN_GPG=no ARCHIVE_SUFFIX=-x64
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: windows
    node_js: "10.16/x86"
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    env: YARN_GPG=no ARCHIVE_SUFFIX=-x86
    script: script/ci/prebuild.sh

  ## PUBLISH STAGE

  - stage: publish
    os: linux
    node_js: "10.16"
    env: IGNORE_SCRIPTS=true
    script: script/ci/package.sh

  fast_finish: true
  allow_failures:
  - os: linux
    node_js: "13"

stages:
- name: test
- name: prebuild
  if: tag IS present
- name: publish
  if: tag IS present

install:
- travis_retry script/ci/install.sh

script:
- travis_retry script/ci/test.sh

deploy:
# Deploy prebuilds to Github releases.
- provider: releases
  draft: false
  file: "${TRAVIS_TAG:-latest}-${TRAVIS_OS_NAME}${ARCHIVE_SUFFIX}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_BUILD_STAGE_NAME = Prebuild"
  api_key:
    secure: EUf/nO4RdGw8ZdW+VdC6wcpgC1TJAvddvHRvWPdssOEsDzGEDvMTp/T1AMEJlAljQDeDUjG4leDiA1bly2Sf/ZUa6G76nn7N1dpfwMTzoKuJKxaB6n3nkyr9lT7pQJ4/S0DKl6P8XbaukBaXREX0lgrDQ7zLsEMzP5RRB9sxmc4KvrYlVAZWImF8vlCmnA3yKhPd6r8d8rvIfkUv70dXjviVlStlBYpkmSMKifDvIZENa90gTgwPXE5SD2FjEgqlN6GjDS1ly413P1ATpZVsuSyZAjESlaqDhsoyuo7QiES3NT3AHNOBdD1eELbHZsMJrsAKE9v/Ylx0Qcq2LsLNgsgBkm6BAmaFt5z80a2RPMiTnRYX6o5vvNhCNhRvez9YKM3rso6jbolPPcsn7vA3XJOrr2Op2EOWP14HkZuhV5zyRcTD2PhXfseFa4JZdDcdUlMDuzmlYCOIIsObOUukvCpT+yoBOtBNbLHy6M+XzeNTST6BkNYyeyJxoYA45ioaQaEky02f1lwV2B+dDW1gy2insU9oU7Wx6bTNW0/KfL4cUlYQLPwHsmGcBWtZjvcGzGsI68rc986F15T8dzHgdeSEpA+8MuDL12cAHmsnlhhxNdAA1wIoTtFScun6d2tgfDD5VraGjZp58++QwO08Pnw9Elz3Cc1Vf+AXc/E4fuU=

# Deploy package including all generated prebuilds to NPM.
- provider: npm
  email: r.w.timmermans@gmail.com
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_BUILD_STAGE_NAME = Publish"
  api_key:
    secure: JROQZBPmUPQL2zS+zDRl0Zg+BiwGQFy/5raJjHObABF77ysvdy5MNFg2TWUabLxrdhq9O84zSySrnWlPYW2kvt2PmtC4vR3RK2i6Yoz6+xd428aypG8HJlITL3aSW+1vV0NbjI0GhwvQBKJAk9+zWjt000b8N/y9tUrFe/ugKfbdJly2cpxg70TGT/pmhkQgJ2g5jTJ3tO5ONDRh+H4yfq/zzRT5FovlGzH3dNLddJJcEOas0WOkS8Lkl/4wx/FAWzzk+o6t9fJesPY3GMK53RvU43itviy2ID8ejkmeGe6a+f7mjODrkjIS5KPDAW9EdfXmZ3f2bX+R7b+9JJYrcDGykkwPQJUr9334zy2fK9xr5lvEYIApCK7HxoXVUU0O2QjCxJS7IrVlnFuMw2ehIRYv2YeBKWjHZG7MQhMUBujlkaum3rj5vEGZey+BBkFF04rC7n2xfWrjIiat2x3zAsfxh/Hrx0GPexHeopo1/GqL7nEuLd4Eq7rJwm+JFX5yxanyF50izmqN6NXnYcwuxn/6ErY6Wi9pGgG7uM6pYmy84ZBYZz+EBzraoePXgDuaz0xaJae57m/2UP8h8Lp6Dim8WSF6k2xUEcHC0W/4IENWwkN+DLhV75hXfFFRlh7ku0bMYtdRoE8/nEnjgSsJe4p8jhPWiqvEIi5bcrGW9W8=
