language: node_js
cache: yarn
dist: bionic

jobs:
  include:
  ## TEST STAGE

  # Test main OSes on Node 10.x branch.
  - os: linux
    node_js: "10.16"
    env: ZMQ_DRAFT=true INCLUDE_COMPAT_TESTS=true

  - os: linux
    env: ALPINE_CHROOT=3.10 ZMQ_DRAFT=true INCLUDE_COMPAT_TESTS=true
    sudo: required

  - os: osx
    env: ZMQ_DRAFT=true
    node_js: "10.16"

  - os: windows
    node_js: "10.16"
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    env: ZMQ_DRAFT=true YARN_GPG=no

  - os: windows
    node_js: "10.16/x86"
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    env: ZMQ_DRAFT=true YARN_GPG=no

  # Test shared libraries on Linux and macOS.
  - os: linux
    node_js: "10.16"
    env: ZMQ_SHARED=true
    addons: {apt: {packages: libzmq3-dev}}

  - os: osx
    node_js: "10.16"
    env: ZMQ_SHARED=true
    addons: {homebrew: {packages: zeromq, update: true}}

  # Test older versions of ZMQ.
  - os: linux
    node_js: "10.16"
    env: ZMQ_VERSION=4.2.4

  # Test recent Node versions.
  - os: linux
    node_js: "12"
    env: ZMQ_DRAFT=true INCLUDE_COMPAT_TESTS=true

  - os: linux
    node_js: "13"
    env: ZMQ_DRAFT=true

  ## PREBUILD STAGE

  - stage: prebuild
    os: linux
    env: ARCHIVE_SUFFIX=-x64
    node_js: "10.16"
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: linux
    env: ALPINE_CHROOT=3.10 ARCHIVE_SUFFIX=-x64-musl
    sudo: required
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: linux
    node_js: "10.16"
    env: ARCH=arm TRIPLE=arm-linux-gnueabihf GCC=8 ARCHIVE_SUFFIX=-armv7
    addons: {apt: {packages: [gcc-8-arm-linux-gnueabihf, g++-8-arm-linux-gnueabihf]}}
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: linux
    node_js: "10.16"
    env: ARCH=arm64 TRIPLE=aarch64-linux-gnu GCC=8 ARCHIVE_SUFFIX=-armv8
    addons: {apt: {packages: [gcc-8-aarch64-linux-gnu, g++-8-aarch64-linux-gnu]}}
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: osx
    node_js: "10.16"
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: windows
    node_js: "10.16"
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    env: YARN_GPG=no ARCHIVE_SUFFIX=-x64
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: windows
    node_js: "10.16/x86"
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    env: YARN_GPG=no ARCHIVE_SUFFIX=-x86
    script: script/ci/prebuild.sh

  ## PUBLISH STAGE

  - stage: publish
    os: linux
    node_js: "10.16"
    env: IGNORE_SCRIPTS=true
    script: script/ci/package.sh

  fast_finish: true
  allow_failures:
  - os: linux
    node_js: "13"

stages:
- name: test
- name: prebuild
  if: tag IS present
- name: publish
  if: tag IS present

install:
- travis_retry script/ci/install.sh

script:
- travis_retry script/ci/test.sh

deploy:
# Deploy prebuilds to Github releases.
- provider: releases
  draft: false
  file: "${TRAVIS_TAG:-latest}-${TRAVIS_OS_NAME}${ARCHIVE_SUFFIX}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_BUILD_STAGE_NAME = Prebuild"
  # api_key:
  #   secure: ...

# Deploy package including all generated prebuilds to NPM.
- provider: npm
  email: r.w.timmermans@gmail.com
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_BUILD_STAGE_NAME = Publish"
  # api_key:
  #   secure: ...

# env:
#   global:
#     secure: ...
