language: node_js
cache: yarn
dist: bionic

jobs:
  include:
  - os: linux
    node_js: "10.16"

script:
- yarn test

deploy:
# Deploy package including all generated prebuilds to NPM.
- provider: npm
  email: r.w.timmermans@gmail.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: JROQZBPmUPQL2zS+zDRl0Zg+BiwGQFy/5raJjHObABF77ysvdy5MNFg2TWUabLxrdhq9O84zSySrnWlPYW2kvt2PmtC4vR3RK2i6Yoz6+xd428aypG8HJlITL3aSW+1vV0NbjI0GhwvQBKJAk9+zWjt000b8N/y9tUrFe/ugKfbdJly2cpxg70TGT/pmhkQgJ2g5jTJ3tO5ONDRh+H4yfq/zzRT5FovlGzH3dNLddJJcEOas0WOkS8Lkl/4wx/FAWzzk+o6t9fJesPY3GMK53RvU43itviy2ID8ejkmeGe6a+f7mjODrkjIS5KPDAW9EdfXmZ3f2bX+R7b+9JJYrcDGykkwPQJUr9334zy2fK9xr5lvEYIApCK7HxoXVUU0O2QjCxJS7IrVlnFuMw2ehIRYv2YeBKWjHZG7MQhMUBujlkaum3rj5vEGZey+BBkFF04rC7n2xfWrjIiat2x3zAsfxh/Hrx0GPexHeopo1/GqL7nEuLd4Eq7rJwm+JFX5yxanyF50izmqN6NXnYcwuxn/6ErY6Wi9pGgG7uM6pYmy84ZBYZz+EBzraoePXgDuaz0xaJae57m/2UP8h8Lp6Dim8WSF6k2xUEcHC0W/4IENWwkN+DLhV75hXfFFRlh7ku0bMYtdRoE8/nEnjgSsJe4p8jhPWiqvEIi5bcrGW9W8=

env:
  global:
    secure: E0JuP0lwV3e9xWf5OUkn4yw8Elslz0obOFxqTItEOMwac4WRFEzZSe51Rit4kZVEGN77m2dzB34bWExWgSMjfh0H5IZQA9uSxCKaJbAGuUzKYHvLKpctlLZ+RcdtTCCnF3N305BMoC0fmplajQx3rf6M3KHL05yYPet5c/4FnP2HRhpEhcv4le1h+O/3GQqVN/+MKpb5mDrZuOPtN/DjCpdKypEBF6O32Ht3AFhIiFMAPzC/0cGnOyKA8hIOBDiDNek2Ie9zbIzBmUX3llvsoJavQi7lgN55FUMqPceqebuzYpcAfTFYt4QME9lNJIbAJBcYDOQ5TileqzVDnoQzZ3Z1PtGJZek9MCm4MeR2C97mNcHTFfD+i7y17kODUqzthMPfCTJt3S+47nFfjK1Fy21Lo+Sw/ScItWtl/rsrxfb6nUVNSglquIJH0xH0gmdfwQA7dGuTNLeI+eslvk4oM+ebD1giDNEmi2KOgC95bDfZgYgaNAf2+NNc5JUUBJ6z/2YuY6xnPh+hpvTLxGGtLOZDekVLf0u5tc4y8INrcWrX2ileMwScx+y0Moj6f0M3D+RICcClVP8NU8hcIZ7gQ1WjwpSQPjWgdeqmY/u4BzE1OYzWkvujF3qMcxj0aONb2/WDW8S/0sUAPUh+kfUL/41obwiGObtmPIS1y5gOfbA=
