language: node_js
cache: yarn

jobs:
  include:
  # Test latest 10.x branch.
  - os: linux
    env: INCLUDE_COMPAT_TESTS=true
    node_js: "10.16"

  - os: linux
    env: ALPINE_CHROOT=true INCLUDE_COMPAT_TESTS=true
    sudo: required

  - os: osx
    node_js: "10.16"

  - os: windows
    node_js: "10.16"

  # Test shared libraries on Linux and macOS.
  - os: linux
    node_js: "10.16"
    env: ZMQ_SHARED=true
    addons: {apt: {packages: libzmq3-dev}}

  - os: osx
    node_js: "10.16"
    env: ZMQ_SHARED=true

  # Test older versions of ZMQ.
  - os: linux
    node_js: "10.16"
    env: ZMQ_VERSION=4.2.4

  # Publish all binaries for Linux and macOS.
  - stage: publish binaries
    node_js: "10.16"
    os: linux
    script: script/ci/release.sh

  - stage: publish binaries
    node_js: "10.16"
    os: osx

  # Publish chroot cross-compiled binaries for Alpine Linux.
  - stage: publish binaries
    node_js: "10.16"
    os: linux
    env: ALPINE_CHROOT=true
    sudo: required

  # Publish cross-compiled binaries for arm & arm64.
  - stage: publish binaries
    node_js: "10.16"
    os: linux
    env: ARCH=arm TRIPLE=arm-linux-gnueabihf GCC=4.8
    install: script/ci/cross-install.sh
    addons: {apt: {packages: [gcc-4.8-arm-linux-gnueabihf, g++-4.8-arm-linux-gnueabihf]}}

  - stage: publish binaries
    node_js: "10.16"
    os: linux
    env: ARCH=arm64 TRIPLE=aarch64-linux-gnu GCC=4.8
    install: script/ci/cross-install.sh
    addons: {apt: {packages: [gcc-4.8-aarch64-linux-gnu, g++-4.8-aarch64-linux-gnu]}}

stages:
- name: test
- name: publish binaries
  if: tag IS present

install:
- travis_retry script/ci/install.sh

script:
- travis_retry script/ci/test.sh


before_deploy:
- ARCHIVE_NAME="\${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-\`uname -m\`.tar"
- npm run prebuild
- tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds"
  .
deploy:
  provider: releases
  draft: false
  prerelease: true
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    condition: $TRAVIS_BUILD_STAGE_NAME = "PUBLISH BINARIES"
  api_key:
    secure: wtBX98vubHC+/5aXLUB3fNZKmnrpLnpgZkbUrfWuq01fEKk/CmL64ArkoqrGOffUhFKRemjgXVPGLF118AZuyS/dW4o05v7KOuBHt7SehhdgO8AVlQ5DVrEQm3gVFNYcusaMRP1eJpSwekHqF7grHk1VTr/uNj01OyAExKynmn6rHJNa/KijRuHsTBEQL7drLOyAHUvodq0c2fclW71H85cTaHXC+NPzydWCWn3k4Z6sGEkQCOIG+v0skWEnN1uyt5MJ89a9WPF8qz/LqVolXKmWHVowpagV2KUQpeZs8Kkao93reWs/MocTXm82gcffBdhqozv6xN55bC1BoJ0oB/S7RHk1dWRgTcPj1hkX5H4X5S8COT9/5FE2tw74jN6mLSKdRy3nNOQZPZuXOn2jlkl2n+b0IwwXBXLfn3ks18AX1Y4kAQBsfPGPM7zPX742Z8cR2rW41aVwWFDVhqI4ITBWOzUC6Cvlm8JT+eADYG5R9sodxS9jEDOH/9Gjx4xRPQK7+Q909x1XmGnVOSFlsCLHT8f7y1mPWTzPT5x57rhkD4BmX4bb0+RAVvDSiVIcko9QznK9lGSNgSX4+Y/sZHW2DHdbo2SdDmLxwUDGAgHXJ3mQNsI0ojAIb/b0d9Ybw4OuWgdMu8aaB+vZuqm1AD57oNomEXnHeMkFlVT42ho=
